; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Estrella Music"
#define MyAppPublisher "JOSPROX MX"
#define MyAppURL "https://github.com/josprox/Estrella-Music-v2"
#define MyAppExeName "harmonymusic.exe"

; Dynamic build path configuration
#define BuildPath "..\build\windows\x64\runner\Release"

; Extract version dynamically from pubspec.yaml if not passed via command line
#ifndef MyAppVersion
  #define PubspecFile AddBackslash(SourcePath) + "..\pubspec.yaml"
  #define FileHandle FileOpen(PubspecFile)
  #define PubspecLine ""
  #define MyAppVersion ""

  #if FileHandle
    #sub ProcessPubspec
      #define PubspecLine FileRead(FileHandle)
      #if Pos("version: ", PubspecLine) == 1
        #define RawVersion Trim(Copy(PubspecLine, 10, 100))
        #define PosPlus Pos("+", RawVersion)
        #if PosPlus > 0
          #define MyAppVersion Copy(RawVersion, 1, PosPlus - 1)
        #else
          #define MyAppVersion RawVersion
        #endif
      #endif
    #endsub
    #define i 0
    #for {i = 0; !FileEof(FileHandle) && (MyAppVersion == ""); i = i + 1} ProcessPubspec
    #expr FileClose(FileHandle)
  #endif

  ; If pubspec.yaml parsing is empty, try getting version from compiled executable
  #if MyAppVersion == ""
    #define MyAppVersion GetVersionNumbersString(BuildPath + "\" + MyAppExeName)
  #endif

  ; Fallback default
  #if MyAppVersion == ""
    #define MyAppVersion "1.0.0"
  #endif
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
AppId={{80EE0D67-75D8-4A3C-8F02-4D42F0642062}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes

; Professional documents (Distribution folder)
LicenseFile=license.txt
InfoBeforeFile=welcome_before_install.txt
InfoAfterFile=readme_after_install.txt

PrivilegesRequired=lowest
OutputDir=.
OutputBaseFilename=EstrellaMusicInstaller
VersionInfoVersion={#MyAppVersion}
SetupIconFile=..\assets\icons\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic polar

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Main Executable
Source: "{#BuildPath}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

; IMPORTANT: Include all DLL dependencies (Dynamic inclusion)
Source: "{#BuildPath}\*.dll"; DestDir: "{app}"; Flags: ignoreversion

; Data folder and assets
Source: "{#BuildPath}\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs

[Registry]
Root: HKA; Subkey: "Software\Classes\estrellamusic"; ValueType: string; ValueName: ""; ValueData: "URL:Estrella Music"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\estrellamusic"; ValueType: string; ValueName: "URL Protocol"; ValueData: ""
Root: HKA; Subkey: "Software\Classes\estrellamusic\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\estrellamusic\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\.myp\OpenWithProgids"; ValueType: string; ValueName: "EstrellaMusicFile"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\EstrellaMusicFile"; ValueType: string; ValueName: ""; ValueData: "Estrella Music File"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\EstrellaMusicFile\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\EstrellaMusicFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
